services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-innovation-frontend
    restart: always
    ports:
      - "3000:80"
    networks:
      - msa-net

networks:
  msa-net:
    external: true
