import os

PERSONAS_LIST_DEFAULT_PAGE_SIZE: int = int(os.getenv("PERSONAS_LIST_DEFAULT_PAGE_SIZE", "100"))
PERSONAS_LIST_MAX_PAGE_SIZE: int     = int(os.getenv("PERSONAS_LIST_MAX_PAGE_SIZE", "200"))

PRODUCTS_BY_TAG_DEFAULT_PAGE_SIZE: int = int(os.getenv("PRODUCTS_BY_TAG_DEFAULT_PAGE_SIZE", "100"))
PRODUCTS_BY_TAG_MAX_PAGE_SIZE: int     = int(os.getenv("PRODUCTS_BY_TAG_MAX_PAGE_SIZE", "200"))

PRODUCTS_BY_BRAND_DEFAULT_PAGE_SIZE: int = int(os.getenv("PRODUCTS_BY_BRAND_DEFAULT_PAGE_SIZE", "100"))
PRODUCTS_BY_BRAND_MAX_PAGE_SIZE: int     = int(os.getenv("PRODUCTS_BY_BRAND_MAX_PAGE_SIZE", "200"))

PRODUCTS_FILTER_DEFAULT_PAGE_SIZE: int = int(os.getenv("PRODUCTS_FILTER_DEFAULT_PAGE_SIZE", "500"))
PRODUCTS_FILTER_MAX_PAGE_SIZE: int     = int(os.getenv("PRODUCTS_FILTER_MAX_PAGE_SIZE", "1000"))
